# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: database.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61tabase.proto\x12\x08\x64\x61tabase\"5\n\x0fGetEdgesRequest\x12\x0f\n\x07\x66rom_id\x18\x01 \x01(\x03\x12\x11\n\tedge_type\x18\x02 \x01(\x03\"I\n\x0eTwoHopsRequest\x12\x0f\n\x07\x66rom_id\x18\x01 \x01(\x03\x12\x12\n\nedge1_type\x18\x02 \x01(\x03\x12\x12\n\nedge2_type\x18\x03 \x01(\x03\"\x1f\n\x10GetEdgesResponse\x12\x0b\n\x03ids\x18\x01 \x03(\x03\x32\x90\x01\n\x08\x44\x61tabase\x12\x42\n\tget_edges\x12\x19.database.GetEdgesRequest\x1a\x1a.database.GetEdgesResponse\x12@\n\x08two_hops\x12\x18.database.TwoHopsRequest\x1a\x1a.database.GetEdgesResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'database_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETEDGESREQUEST']._serialized_start=28
  _globals['_GETEDGESREQUEST']._serialized_end=81
  _globals['_TWOHOPSREQUEST']._serialized_start=83
  _globals['_TWOHOPSREQUEST']._serialized_end=156
  _globals['_GETEDGESRESPONSE']._serialized_start=158
  _globals['_GETEDGESRESPONSE']._serialized_end=189
  _globals['_DATABASE']._serialized_start=192
  _globals['_DATABASE']._serialized_end=336
# @@protoc_insertion_point(module_scope)
