import typing as t

class Database:
    def __init__(self) -> None: ...
    def get_edges(self, from_id: int, edge_type: int) -> t.List[int]: ...
    def two_hops(self, from_id: int, edge1_type: int, edge2_type: int) -> t.List[int]: ...